//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace if2ktool.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("if2ktool.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ; This script creates a JSON file using foobar2000&apos;s &quot;Text Tools&quot; plugin for use in if2ktool, containing information on each track:
        ///; 1. Read the patterns from the json_patterns.txt file into some variables (it&apos;s easier than declaring them here)
        ///; 2. Open foobar2000 to the &quot;Album List&quot; window (this component should be installed by default). We use album list to provide a context for all music.
        ///; 3. Right click &quot;All Music&quot; to show the context menu
        ///; 4. Navigate to &quot;Utilities -&gt; Text Tools -&gt; Advanced&quot; to [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CreateLookupJSON {
            get {
                return ResourceManager.GetString("CreateLookupJSON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] CreateLookupJSON_exe {
            get {
                object obj = ResourceManager.GetObject("CreateLookupJSON_exe", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $pad( ,4){$char(13)$char(10)$pad( ,8)&quot;index&quot;: $sub(%list_index%,1),$char(13)$char(10)$pad( ,8)&quot;title&quot;: &quot;$replace($replace($replace([$meta(Title)],\,\\),&quot;,\&quot;),$tab(),\t)&quot;,$char(13)$char(10)$pad( ,8)&quot;artist&quot;: &quot;$replace($replace($replace([%artist%],\,\\),&quot;,\&quot;),$tab(),\t)&quot;,$char(13)$char(10)$pad( ,8)&quot;album&quot;: &quot;$replace($replace($replace([%album%],\,\\),&quot;,\&quot;),$tab(),\t)&quot;,$char(13)$char(10)$pad( ,8)&quot;trackNumber&quot;: $replace(&quot;[%tracknumber%]&quot;,&quot;&quot;,null),$char(13)$char(10)$pad( ,8)&quot;path&quot;: &quot;$replace($replace($replace([%p [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JSON_Patterns {
            get {
                return ResourceManager.GetString("JSON_Patterns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap no_image_dots {
            get {
                object obj = ResourceManager.GetObject("no_image_dots", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
